### ISSUE TITLE
command chaining with export/import + targeting breaks saferc

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#100]
I ran a `safe target dev -- export secret | safe target bosh-lite -- import` today multiple times, and each time, it corrupted my `~/.saferc` file.

```
$ safe target dev -- export secret | safe target bosh-lite -- import
Now targeting bosh-lite at https://10.244.8.2:443 (skipping TLS certificate verification)

Now targeting dev at http://localhost:8200

wrote secret/boshlite/vault/certs/ca
wrote secret/boshlite/vault/certs/consul
10:46:38 gfranks@chameau-grincheux.local {~/code/starkandwayne/g2-deployments/vault-deployments}(master)[3]
$ safe tree
You are not targeting a Vault.
Try safe target http://your-vault alias
 or safe target alias
10:46:41 gfranks@chameau-grincheux.local {~/code/starkandwayne/g2-deployments/vault-deployments}(master)[3]
$ cat ~/.saferc
Aliases:
  bosh-lite: https://10.244.8.2:443
  dev: http://localhost:8200
Current: dev
SkipVerify:
  https://10.244.8.2:443: true
Targets:
  http://localhost:8200: REDACTED
  https://10.244.8.2:443: REDACTED
ACTED
```

(the end of the final target's password remained on a new-line at the end of the file)

The amount data at the end seems to match up with the difference between the `Current: dev` and `Current: bosh-lite` files. I suspect we're not closing the written file from the first safe target quick enough, and then it stomps on the second target's update when safe exits.

**Comment by jhunt** [comment]
Perhaps we should delay the configuration update until after we are done executing chained commands.  I.e. `safe target` should set the desired target _in-memory_, and flag that a config write needs to happen.  Then, right before we exit, we trigger the write (if so flagged).  This would lead to semantics of "last target wins" which matches the mental model.

Exclusive file access and a wait loop might also be helpful to avoid the truncation in the event of a "quick" command pipeline like the nonsensical `safe target a | safe target b`

**Comment by jhunt** [comment]
A better solution may be to support a `-t` for that kind of thing, or avoid the whole problem by introducing `safe backup target-a backup-target`
