### ISSUE TITLE
Add ability to re-key Vault + GPG encrypt the unseal keys

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#103]
It would be super cool if we could have a `safe rekey` command that would re-key an existing Vault with new unseal keys, gpg encrypting the new keys for safe-keeping.

Maybe something like:

```
safe rekey --gpg user2@email.com --gpg geoff@email.com --unseal-count 4 --keys-to-unseal=2
```

If only one user was specified via `--gpg`, the unseal keys (count specified via `--unseal-count`) will be encrypted with that key, and emailed to the user. If more than one `--gpg` entry is specified, that will determine the number of unseal keys to be generated. If both `--unseal-count` and multiple `--gpg` entries are specified, it will throw an error if the numbers do not match. It would also error if the value for `--unseal-count` is less than `--keys-to-unseal`

The value of `--gpg` should be an email address associated with the GPG public key to be used. `safe` would do a lookup of the email to retrieve the pub key, and then email the encrypted results to the user (also saving to local output in case email is disabled/blocked). Confirmation that at least `--keys-to-unseal` number of recipients have received their keys will ensure that a rekey does not leave Vault in an un-unsealable situation

If no `--gpg` entries are specified, output of the rekey will be printed to STDOUT, and it is the caller's responsibility to save the new unseal keys

**Comment by jhunt** [comment]
Sure would be super cool.

How do you propose we handle the issue of SMTP server configuration?

**Comment by geofffranks** [comment]
Latest thoughts are to ignore the smtp integration, and leave that to the end user to distribute via email, GitHub, or saving to vault

Should have a PR in a couple days

**Comment by jhunt** [comment]
Where is it going to get the keys?

**Comment by geofffranks** [comment]
It pulls from the local gpg keyring, searching via email/name, and taking the first result.

We didn't go with the single-GPG key encrypting everything approach, as vault has built-in functionality to encrypt each unseal key with a different PGP key. For that scenario, you could just `safe rekey | gpg -e`

**Comment by thomasmmitchell** [comment]
Good to close this @geofffranks ?

**Comment by thomasmmitchell** [comment]
It's in 0.3.0
