### ISSUE TITLE
Pulling system root CAs to validate doesn't work against the released copy of safe

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#113]
Targeting a Vault with a custom root CA that's added to my system keychain as a trusted root still requires a `-k` to skip ssl verification, when using the released copy of safe. If I build a fresh copy using golang 1.9, it works as expected.

Any chance we can update safe to build against v1.9, or determine why the released copy doesn't work as a hand-built copy?

**Comment by jhunt** [comment]
Are you running Vault with a certificate signed by an authority you popped into your system chain?  Trying to reproduce.

**Comment by geofffranks** [comment]
Correct, it's an in-house Root CA that's in the system keychain as an always-trusted root.

**Comment by jhunt** [comment]
Literally the only way around this seems to be building safe on darwin.

**Comment by jhunt** [comment]
@geofffranks have you seen https://github.com/golang/go/issues/18141 and https://github.com/golang/go/issues/18203?

**Comment by geofffranks** [comment]
Similar code and support is in spruce, and working for us, though spruce is built via Golang 1.9 on Linux. Perhaps that will work here too?

**Comment by jhunt** [comment]
In that case try 0.5.0, since that should have been rebuilt with 1.9

**Comment by jhunt** [comment]
Or maybe not.  I'll have to talk to @thomasmmitchell since it seems per his commits to dockerfiles, we should be using 1.9

**Comment by jhunt** [comment]
Ha!  Turns out it's because the safe pipeline configuration was forcing 1.8.

I bumped it to 1.9 and it's running through the pipeline now.  If all goes well, I'll cut 0.5.1 with macOS cert support this morning.

**Comment by thomasmmitchell** [comment]
Initially, the `latest` tag was stuck on, like... 1.6, so any pipelines made before then had to specify their go version explicitly. I bumped `latest` to 1.9, and should remember to bump it again when 1.10 comes out.

**Comment by jhunt** [comment]
I still think I'll be pinning versions for all my go pipelines, so that I can control _when_ I want to deal with the fall-out of having to upgrade go versions.  Apparently 1.9 is a little more picky (if you can believe it) than previous versions of the compiler / toolchain.

**Comment by jhunt** [comment]
@geofffranks try out 0.5.1, it seems to be working admirably in my test setup with a custom, mac-trusted CA and an issued cert.

**Comment by geofffranks** [comment]
Thanks! Will give it a shot after the holiday

**Comment by geofffranks** [comment]
Yup, everything looks great here, thanks!
