### ISSUE TITLE
path/key ambiguousness when key contains colons

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/safe#121]
Safe prevents you from writing to vault with a path that contains colons, but you can have keys that contain colons, such as:
```
safe set secret/xxxx a/very:weird:value/bork=hahahahaha
```

However, trying to get that value results in the following:
```
> safe get secret/xxxx:a/very:weird:value/bork=hahahahaha
!! no secret exists at path `secret/xxxx:a/very:weird`
```

Note: Not sure what happens if you mass-import a json file that contains paths that contain colons, haven't tried that scenario

**Comment by geofffranks** [comment]
In my recent experience, it failed on import. There were some export complaints involving colons with no data underneath it, but then import failed for different paths with colons, which did have data nested inside them.

**Comment by thomasmmitchell** [comment]
I had thought about this when implementing the path:key stuff. I think the consensus around was "nobody would ever put colons in their paths."

Well... shit.

Soooo... backslash escapes, maybe?

**Comment by jhunt** [comment]
Is this a real problem people are having, or a "hey, I wonder if..." problem?
