### ISSUE TITLE
`safe delete -Rf` doesn't delete anything

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/safe#122]
When running the `safe delete -Rf`, the given path is not removed.

Doesn't work:
safe delete -R secret/west/us/sandbox/certificates
safe delete -Rf secret/west/us/sandbox/certificates

Does work:
safe paths secret/west/us/sandbox/certificates | xargs safe delete

**Comment by jhunt** [comment]
Can you provide more extensive logs to help me reproduce this?

**Comment by jhunt** [comment]
nm, got it.

:ninja:
