### ISSUE TITLE
result of listing a nonexistent path implies a paths existence

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/safe#123]
The Vault key/value secret backend API's list endpoint returns an empty list when called on a non-existent path. That's lame. We can work around it though.

If we get back an empty list from that call, we can check if its a secret (a leaf node). If it isn't we should return an error signifying that nothing exists at that path.

**Comment by jhunt** [comment]
@thomasmmitchell I'm not sure I understand the issue here, since we have this code already (and have since 2016):

```
func (v *Vault) List(path string) (paths []string, err error) {
    req, err := http.NewRequest("GET", v.url("/v1/%s?list=1", path), nil)
    // handler err

    res, err := v.request(req)
    // handle err

    switch res.StatusCode {
    case 200:
        break
    case 404:
        req, err = http.NewRequest("GET", v.url("/v1/%s", path), nil)
        // handle error
        res, err = v.request(req)
        // handle error

        switch res.StatusCode {
        case 200:
            break
        case 404:
            err = NewSecretNotFoundError(path)
            return
        }
    }

    // ...
}
```

**Comment by thomasmmitchell** [comment]
What I was saying is that Vault doesn't 404 in this scenario. It returns 200 and an empty list.

For there to be an empty list under a path that exists, the path would have to be a secret (a secret has no subpaths). If it isn't a secret, we can conclude then that the path doesn't exist.

**Comment by jhunt** [comment]
Here's what I see:

(run under `safe local` with vault 0.9.0:)
```
→  safe tree --keys
.
└── secret
    └── handshake
        └── :knock

→  safe curl secret/handshake
HTTP/1.1 200 OK
Content-Length: 181
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 04 Apr 2018 00:13:37 GMT

{"request_id":"...","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"knock":"knock"},"wrap_info":null,"warnings":null,"auth":null}

→  safe curl secret/handshake?list=1
HTTP/1.1 404 Not Found
Content-Length: 14
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 04 Apr 2018 00:14:25 GMT

{"errors":[]}
```

What am I missing here?

**Comment by jhunt** [comment]
for the negative case (same vault):

```
→  safe curl secret/foo/bar?list=1
HTTP/1.1 404 Not Found
Content-Length: 14
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 04 Apr 2018 00:17:07 GMT

{"errors":[]}
```

**Comment by thomasmmitchell** [comment]
Dunno. Would need to ask January me what the circumstances around it were at this point. Don't know which build or version of safe. Don't know if the problem was actually something else that looked like this. Guess its lost to time at this point.

**Comment by jhunt** [comment]
I did find this little gem in the bowels of the Vault CLI:

```
    //need to check if length of list is 0 because prior to vault 0.6.0, no 404 is
    //given for attempting to list a path which does not exist.
```

**Comment by thomasmmitchell** [comment]
What version is our stackscale running?
