### ISSUE TITLE
`safe x509 renew` (or reissue) command

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/safe#128]
I would like to be able to do the following:

```
safe x509 renew secret/lab/certs/lab.starkandwayne.com
safe x509 renew secret/lab/certs/lab.starkandwayne.com --ttl 2y
safe x509 renew secret/lab/certs/lab.starkandwayne.com --add new.name.in.dns --remove 10.0.0.4
```
And have `safe` Do The Right Thing™️, finding the CA and modifying the SANs.

**Comment by kwilczynski** [comment]
Hi @jhunt,

Thank you for working on this, this is an amazing feature!

I reaching out, as I need to ask - any idea if this can be made to support Elliptic Curve type certificates? By looking at the code in the Pull Request my impression would be that only RSA is supported (given the key bits sizes, etc).

What do you think?

**Comment by jhunt** [comment]
It does currently only support RSA.  If you want to work on EC, and the golang crypro libs support it (I haven't checked), I'd be happy to field a PR or two.

**Comment by kwilczynski** [comment]
Hi @jhunt,

Go most definitely supports Elliptic Curves (actually, a plethora of modern ciphers, MACs, hashes, etc.), and everything works very well, indeed - I work a lot with HTTP/2 and gRPC, etc.

I will try to help and open a Pull Request, but not sure about the time frame (too much to work work-wise, thus it might be a weekend hacking project, etc.).
