### ISSUE TITLE
LIST method not supported by curl?

### ISSUE THREAD

**Issue by lvets** [starkandwayne/safe#130]
Hello,

Is there a specific reason not to allow the LIST method when using the `curl` option?

**Comment by jhunt** [comment]
Most likely because it's not a standard HTTP method.  We only restrict the method so that we know whether or not we are obligated to provide a request body or not.

Vault seems to be abusing LIST as a way around a GET with `?list=true` query string.  I'll update safe to accommodate, treating LIST as if it were a GET.

**Comment by jhunt** [comment]
Upon further inspection, it appears we don't actually limit the method; we just say we do in the documentation.  Sneaky.

I'll update the docs.

@lvets is safe specifically prohibiting `safe curl LIST secret` for you?

**Comment by lvets** [comment]
I'm currently seeing this:
```
$ safe version
safe v0.6.3
$ safe curl LIST /auth/approle/role
HTTP/1.1 405 Method Not Allowed
Content-Length: 60
Cache-Control: no-store
Content-Type: application/json
Date: Fri, 02 Mar 2018 17:13:35 GMT

{"errors":["1 error occurred:\n\n* unsupported operation"]}
$
```
I was under the impression this would work (https://www.vaultproject.io/api/auth/approle/index.html), but after reading the help of the curl method I thought it was not supprted at all...

**Comment by jhunt** [comment]
Yeah, the 405 is coming from Vault itself.

Try this:

```
DEBUG=on safe curl LIST /auth/approle/role
```

**Comment by lvets** [comment]
Lol, it seems to be the extra "/" you're sending:
```
$ safe vault list /auth/approle/role 
Keys
----
<SHOWS APPROLE POLICIES>

$ DEBUG=on safe curl LIST /auth/approle/role
Request:
LIST /v1//auth/approle/role HTTP/1.1
Host: <HOSTNAME>
X-Vault-Token: <VAULT_TOKEN>


----------------
Response:
HTTP/1.1 405 Method Not Allowed
Content-Length: 60
Cache-Control: no-store
Content-Type: application/json
Date: Sat, 03 Mar 2018 02:20:47 GMT

{"errors":["1 error occurred:\n\n* unsupported operation"]}

----------------
HTTP/1.1 405 Method Not Allowed
Content-Length: 60
Cache-Control: no-store
Content-Type: application/json
Date: Sat, 03 Mar 2018 02:20:47 GMT

{"errors":["1 error occurred:\n\n* unsupported operation"]}

$ curl -k --header "X-Vault-Token: <VAULT_TOKEN>" \
--request LIST \
https://<HOSTNAME>/v1/auth/approle/role
{"request_id":"<REQUEST_ID>","lease_id":"","renewable":false,"lease_duration":0,"data":{"keys":["<ALL APPROLE POLICIES>",]},"wrap_info":null,"warnings":null,"auth":null}
$ curl -k --header "X-Vault-Token: <VAULT_TOKEN>" \
--request LIST \
https://<HOSTNAME>/v1//auth/approle/role
$
```

**Comment by jhunt** [comment]
You mean the extra leading slash you're supplying? ;)

We've fixed this before, just need to see if it didn't get propagated to curl.

**Comment by jhunt** [comment]
Silly commit message closing tickets.  @lvets try latest master and if that works for you I'll cut a new point release.

**Comment by lvets** [comment]
Development version works as I expect, thanks! 😄

**Comment by jhunt** [comment]
0.6.4 is out with this fix.  Enjoy!
