### ISSUE TITLE
Support for SOCKS5 proxy

### ISSUE THREAD

**Issue by drnic** [starkandwayne/safe#132]
I'm using genesis, which uses safe, from in front of a SOCKS5 jumpbox. Could we pair and add support for this?

Something we could perhaps borrow from is https://github.com/cloudfoundry-incubator/credhub-cli/blob/master/credhub/socksify.go

**Comment by drnic** [comment]
Closing. `HTTPS_PROXY=socks5://localhost:9999` seems to work ok. Will reopen if I find out otherwise.

**Comment by jhunt** [comment]
Glad to be of assistance!
