### ISSUE TITLE
Reverse Proxy support

### ISSUE THREAD

**Issue by mxplusb** [starkandwayne/safe#135]
I'm using the safe BOSH release behind an SSL-terminated reverse proxy, and the client will target an installation, but it cannot take any action past that point:

```
λ  ~  safe targets

Known Vault targets - current target indicated with a (*):
(*) admin                   https://vault.cf.domain.com

λ  ~  safe unseal
!! Get http://vault.cf.reboot3times.org:8484/strongbox: dial tcp 1.2.3.4:8484: connect: connection refused; are you targeting a `safe' installation?
```

I would expect the client to use the same endpoint as it's base target. I can only expose 80 and 443 through my firewall, so the `safe` CLI would have to be able to talk over SSL.

**Comment by jhunt** [comment]
In this case, you'll have to settle for `safe vault operator unseal` and lose the benefits of strongbox.  Strongbox is an add-on bit of code; it specifically stays out of the way of the actual Vault API, lets it do something unfortunate while handling credentials.
