### ISSUE TITLE
Bash compatible `safe env`

### ISSUE THREAD

**Issue by zerok** [starkandwayne/safe#146]
Hi 🙂

Right now `safe env` doesn't print environment variables in a way that is easy to consume by bash and other shells.

Would something like this be an option for you? 

```
$ source $(safe env --bash)
```

If so, I'll try to put a PR together in the next couple of days.

Additionally, I noticed that `VAULT_SKIP_VERIFY` is not included in the output. I'd add that in the same PR if that's alright with you 🙂

**Comment by jhunt** [comment]
Sounds great!  This is something that I've always wanted to do, but never found the time.
