### ISSUE TITLE
safe not accepting tokens from stdin

### ISSUE THREAD

**Issue by lrstanley** [starkandwayne/safe#149]
Can't seem to use stdin, e.g:
```console
$ safe auth token <(cat ~/.path-to-my-token-file)
Authenticating against my-vault at https://vault.my-host.com:8200
Token:
```

Still prompts for the token. I see the following mentions adding support for it though:
https://github.com/starkandwayne/safe/issues/21

```console
$ safe version
safe v0.9.0
```

Definitely useful for automation scripts. Safe is much better in this aspect due to the `path`, `ls`, etc sub-commands which take more work to replicate using the regular vault cli.

**Comment by jhunt** [comment]
@thomasmmitchell ^^

**Comment by thomasmmitchell** [comment]
What you're doing there isn't putting anything into stdin. The value of <(cat ~/.path-to-my-token-file) is a string which is the path of a pseudofile, and then that is given as an argument. You've effectively written
`safe auth token /dev/fd/63`
or something to that effect.

What you intended was
`cat ~/.path-to-my-token-file | safe auth token`

which works for me :).
