### ISSUE TITLE
safe auth ldap fails on windows

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#151]
Trying to auth to vault on windows using `safe auth ldap` fails for me, with `Vault API errored: LDAP Search for binddn 0 or not unique` (v0.9.2). Using the safe to authenticate via Linux succeeds. Not sure if it could be environment specific, as this windows VM is pretty locked down, but thought i'd mention it in case it's something that can be fixed. Not at all urgent

**Comment by daviddob** [comment]
It may be environmental, as I have a few teams using LDAP auth on windows currently via safe. Does LDAP auth work via the native vault cli on those machines?

**Comment by daviddob** [comment]
Just got a report from one of the teams regarding a developer encountering this issue. Going to look into it tomorrow.
