### ISSUE TITLE
`safe target --json reports` inaccurate "verify" value

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/safe#162]
`safe targets --json` produced the following output (trimmed):

``` 
 {
    "name": "unbreakable-donjon",
    "url": "http://127.0.0.1:8201",
    "verify": false
  }
```

However, `safe target --json` produced this:

```
{
  "name": "unbreakable-donjon",
  "url": "http://127.0.0.1:8201",
  "verify": true
}
```

Since "unbreakable-donjon" is a `safe local` creation, communicating over http, its virtually impossible to have verify:true.

**Comment by jhunt** [comment]
Here's what my testing uncovered:

```
→  cat ~/.saferc | spruce json | jq -r '.vaults["infrangible-castle"]'
{
  "skip_verify": false,
  "token": "f769d1a7-458f-748f-bb90-1f517737425b",
  "url": "http://127.0.0.1:8201"
}

→  safe targets --json | jq -r '.[] | select(.name == "infrangible-castle")'
{
  "name": "infrangible-castle",
  "url": "http://127.0.0.1:8201",
  "verify": false
}

→  safe target --json
{
  "name": "infrangible-castle",
  "url": "http://127.0.0.1:8201",
  "verify": true
}
```

That is, `safe targets` is the correct one, and `safe target` is in error.  While it is true that you cannot _verify_ the certificate of an HTTP endpoint, the disposition should be thought of more as `!skipVerify`, and since we don't explicitly SKIP the verification for the local vault, `verify: true` makes sense.

**Comment by jhunt** [comment]
(Incidentally, all of this is mostly caused by architectural missteps in the design of the `rc` module, which is also what's going on in #160)

**Comment by dennisjbell** [comment]
Sorry, yes.  I discovered this was the case while researching further into it and pushed a fix to master.  I should have updated this ticket once the discovery was made and again when it was fixed.  Thank you for investigating, sorry for wasting your time.
