### ISSUE TITLE
safe local doesn't work with vault v1.1.2

### ISSUE THREAD

**Issue by sriniketh923** [starkandwayne/safe#184]
When issuing the safe x509 issue command, the secrets path doesn't exist because it was not created by default when safe local -m command was issued.

**Comment by thomasmitchell** [comment]
Fixed in 31671ac3c803fbb82e8d4910a3ff3efbbcd81f6f

**Comment by thomasmitchell** [comment]
Release coming after I finish up one more thing.

**Comment by jhunt** [comment]
I believe this has been fixed in v1.2.0 (https://github.com/starkandwayne/safe/releases/tag/v1.2.0)

Can you take that for a spin, @sriniketh923 ?  Should be able to brew it up-to-date...

**Comment by sriniketh923** [comment]
Updated my safe using brew and it works fine now.
