### ISSUE TITLE
`safe {status,seal,unseal}` should work for single-instance Vaults

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/safe#191]
It would be nice to retain the old ways for clustered Vaults (bouncing through strongbox) if we can detect that; otherwise it would be nice to work on a single instance.

Proposed workflow:

If we can't connect to `$ip:8484`, just pretend we are a single instance and perform the action against a single vault backend.

**Comment by thomasmitchell** [comment]
This would be fine if we get a deny from the backend, but is problematic for places where firewalls will just drop packets. May add a flag to `safe target` to allow targets to be marked as no-strongbox. Safe locals should make these kinds of targets.

**Comment by thomasmitchell** [comment]
This was fixed and released in v1.4.0
