### ISSUE TITLE
Support Vault Enterprise Namespaces

### ISSUE THREAD

**Issue by powhapki** [starkandwayne/safe#194]
Hi,
I'm using safe with HashiCorp Vault OSS version, but I have to replace it with Vault Enterprise Edition. 
I'm under testing safe with Vault Enterprise, but safe dose not support NameSpace.

eg) With NameSpace, safe encountered the error.
➜  ~ safe paths
!! 403 Forbidden: 1 error occurred:
	* permission denied

Please help me out.

**Comment by thomasmitchell** [comment]
safe paths without an argument assumes `secret` as the path. This can't change for backwards-compatibility reasons.

I would not be opposed to allowing the specification of a namespace through a flag when targeting. In the interim, I believe a workaround is to give the namespace as part of the path. If your namespace is `ns1`, then I believe you can use, for example, `safe paths ns1/secret`

**Comment by powhapki** [comment]
Thanks for the tip. It works.

**Comment by powhapki** [comment]
Resolved.

**Comment by thomasmitchell** [comment]
Reopening because we can't do mount type detection right now if there's a namespace.

**Comment by thomasmitchell** [comment]
This should be addressed by 17856004fa5396188eb95db11047b5231aee0429

@powhapki Are you able to take a build for a spin to see if this solves for your use cases?
There is now a `-n` flag to `target` to specify a namespace to be used for that target.

**Comment by powhapki** [comment]
Hi, You almost fixed, except the output of safe env.
`-n` flag works, so I can access kv2 just like kv1. But the output of safe env is weird.
Other than, everything seems good. 

➜  bin ./safe env --bash
\unset VAULT_SKIP_VERIFY;
\export VAULT_ADDR=http://10.7.0.13:8200;
\export VAULT_TOKEN=s.sdfsdfsdfsdf;

➜  bin ./safe get  kv2/test
--- # kv2/test
val: XMn7MqzV4oFbPYkpX2ns

➜  bin ./safe paths  kv2/test
kv2/test
kv2/test/random
➜  bin ./safe get kv2/test/random:value
pQi8IJVsqRKMKNdBQLwa
➜  bin

**Comment by thomasmitchell** [comment]
the output format of the bash env is correct. Putting a backslash before the command causes the shell to ignore aliases in interactive mode.

However, this does highlight that a couple of the newer environment variables are missing and should be added in before the next release.

**Comment by powhapki** [comment]
I think safe env need to print out "VAULT_NAMESPACE" also, but it's omitted.
That's why I thought almost fixed.

**Comment by thomasmitchell** [comment]
Fixed that this morning with 80f20fe9ceb5cf16c303389ac52f448be2cf0d77

**Comment by powhapki** [comment]
I'll rebuild & test again, then let you know the result.

**Comment by powhapki** [comment]
Beautiful, I finally get the NAMESPACE Info.
I don't know how to thank you enough. If there's further help, I'll request.

\export VAULT_ADDR=http://10.7.0.13:8200;
\export VAULT_TOKEN=s.w12123;
\unset VAULT_SKIP_VERIFY;
\export VAULT_NAMESPACE=ns1;
