### ISSUE TITLE
Does random support kv2?

### ISSUE THREAD

**Issue by powhapki** [starkandwayne/safe#195]
Im wondering if safe gen support kv2 or not?
If so, how can I use safe gen with kv2? If not, do you have any plan for support kv2?
Please let me know.

Thank you.

**Comment by thomasmitchell** [comment]
All commands should support KV v2. It should work in the same way that v1 works. Is there a particular issue you are having?

**Comment by powhapki** [comment]
I'd like to create random password with kv2. But it failed. and safe paths couldn't get the path with kv2.
Is this related with Vault Policy or safe? If this is a Vault problem, I'll contact to hashicorp.
Please let me know.

➜  ~ safe gen 20 ns1/kv2/data/test/random value
!! 400 Bad Request: no data provided
➜  ~ safe paths ns1/kv2/data/test
!! 1 error occurred:
	* unsupported operation

**Comment by thomasmitchell** [comment]
Probably has something to do with namespaces and how the path gets built in safe. I don’t have an enterprise vault available to test against, however. If there are any traces that you can provide by exporting ‘DEBUG=1’, sanitized if necessary, I would be happy to take a look

**Comment by powhapki** [comment]
Hi Thomas,

Thank you for the guide. I'll test with DEBUG and update more.

**Comment by powhapki** [comment]
During executing safe paths ns1/kv2/data/test, I got the following error.
kv2 is kv2, but using path with v2. Can I specify the version of kv with safe?

Request:
GET /v1/ns1/kv2 HTTP/1.1
Host: 10.7.0.13:8200


Response:
HTTP/1.1 403 Forbidden
Content-Length: 60
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 14:27:13 GMT

{"errors":["1 error occurred:\n\t* permission denied\n\n"]}

**Comment by powhapki** [comment]
I found the way to use safe paths with kv2.
The thing is safe gen isn't working with kv2.

**Comment by powhapki** [comment]
Hi I found that kv1 and kv2 use different path. Can you help me out this?
I'd like use safe gen with kv2.

[https://www.vaultproject.io/api/secret/kv/kv-v1.html](https://www.vaultproject.io/api/secret/kv/kv-v1.html)
[https://www.vaultproject.io/api/secret/kv/kv-v2.html](https://www.vaultproject.io/api/secret/kv/kv-v2.html)

**Comment by powhapki** [comment]
First out with kv1.

➜  ~ safe gen 20 ns1/kv/hello/random value
Request:
GET /v1/sys/internal/ui/mounts HTTP/1.1
Host: 10.7.0.13:8200


Response:
HTTP/1.1 200 OK
Content-Length: 181
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 16:11:05 GMT

{"request_id":"62e6ac65-96ec-7acb-db6d-e50e5b96447f","lease_id":"","renewable":false,"lease_duration":0,"data":{"auth":{},"secret":{}},"wrap_info":null,"warnings":null,"auth":null}

Request:
GET /v1/ns1/kv/hello/random HTTP/1.1
Host: 10.7.0.13:8200


Response:
HTTP/1.1 200 OK
Content-Length: 196
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 16:11:05 GMT

{"request_id":"ca7cc0b7-3c64-066c-6321-3ca8a924f403","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"value":"4f2vU3UsASIePpFV41br"},"wrap_info":null,"warnings":null,"auth":null}

Request:
PUT /v1/ns1/kv/hello/random HTTP/1.1
Host: 10.7.0.13:8200

{"value":"h3IwMfzJlYzPCIihlFD4"}

Response:
HTTP/1.1 204 No Content
Content-Length: 0
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 16:11:05 GMT


Second out with kv2.
➜  ~ safe gen 20 ns1/kv2/data/test/random val1
Request:
GET /v1/sys/internal/ui/mounts HTTP/1.1
Host: 10.7.0.13:8200


Response:
HTTP/1.1 200 OK
Content-Length: 181
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 16:13:03 GMT

{"request_id":"5a1b9c26-daba-6164-e216-fae1ef678351","lease_id":"","renewable":false,"lease_duration":0,"data":{"auth":{},"secret":{}},"wrap_info":null,"warnings":null,"auth":null}

Request:
GET /v1/ns1/kv2/data/test/random HTTP/1.1
Host: 10.7.0.13:8200


Response:
HTTP/1.1 404 Not Found
Content-Length: 14
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 16:13:03 GMT

{"errors":[]}

Request:
PUT /v1/ns1/kv2/data/test/random HTTP/1.1
Host: 10.7.0.13:8200

{"val1":"8hH890qKaExaSdAhQ2PS"}

Response:
HTTP/1.1 400 Bad Request
Content-Length: 32
Cache-Control: no-store
Content-Type: application/json
Date: Wed, 13 Nov 2019 16:13:03 GMT

{"errors":["no data provided"]}

**Comment by thomasmitchell** [comment]
Ah. So KV type is determined by looking up the mount automatically. But _that_ code won't use your "namespace" in the path. So, yeah, going to need to support a --namespace flag directly in the target command.

**Comment by thomasmitchell** [comment]
Linking to #194
