### ISSUE TITLE
Safe: unsupported protocol scheme

### ISSUE THREAD

**Issue by Aracki** [starkandwayne/safe#196]
Any of `safe` commands are returning: 

`!! Get //:80/v1/sys/mounts: unsupported protocol scheme ""` or
`!! Get //:80/v1/sys/internal/ui/mounts: unsupported protocol scheme ""`

Outputs from `safe targets` & `safe env` seems right to me.

Safe version: `v1.4.1`
Vault version: `v1.2.4`

**Comment by thomasmitchell** [comment]
hrm. This doesn't give me much to go on. Can I get an example of `safe target` output?

**Comment by Aracki** [comment]
```
Currently targeting devops-staging at https//vault.<URL>.com
Uses Strongbox at http://:8484/strongbox
```

**Comment by Aracki** [comment]
I've tried to reinstall `safe` and run it against the new vault cluster. Now I'm getting the similar message:

```
!! Transport Error: Get //:80/v1/sys/internal/ui/mounts: unsupported protocol scheme ""
```

**Comment by Aracki** [comment]
I have found the issue. Accidentally when I was setting the target I was doing:
`safe target https//<URL>.com devops-staging` (missing `:` after `https`)

Now `safe targets` returns:
```
Currently targeting devops-staging at https://vault.<URL>.com
Uses Strongbox at http://vault.<URL>.com:8484/strongbox
```

Thanks @thomasmitchell for pointing me to the right direction!
