### ISSUE TITLE
!! invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Aracki** [starkandwayne/safe#202]
For a various kind of commands (`safe get`, `safe ls`,...) I'm getting this error. 
```
!! invalid character '<' looking for beginning of value
```

Happening in both `1.4.1` & `1.5.1` versions.

**Comment by thomasmitchell** [comment]
This occurs when whatever safe is targeting returns HTML (it expects JSON).

Typically means something else is going wrong with what you're targeting, but the error isn't particularly helpful (should probably fail before getting to JSON parsing by checking the Content-Type header).

**Comment by thomasmitchell** [comment]
Addressed by fb6b03c55b96614be934692f2b779f5dad1f5734

vaultkv now, if it fails to unmarshal the body as JSON, then checks the Content-Type header of the request and returns a slightly more specific error message.
