### ISSUE TITLE
safe uuid

### ISSUE THREAD

**Issue by thomasmitchell** [starkandwayne/safe#214]
make uuids. put them in the vault.

**Comment by gerardocorea** [comment]
would this mean generating a uuid and set them in the vault path provided?

**Comment by thomasmitchell** [comment]
That is the idea!

I would use https://github.com/pborman/uuid to generate a cryptographically random UUID (uuid v4 is really the version most people care about in this context). Then just write it into the Vault in the same way that `safe gen` would.

Call signature probably looks something like

`safe uuid path/to/secret:key`

with a default key name of `uuid` if the key is not present in the path.

**Comment by gerardocorea** [comment]
what would the proper way to push a branch be for this open issue? Should I fork the repo instead?

**Comment by thomasmitchell** [comment]
yup. fork the repo, and then PR it back once you're set.

**Comment by gerardocorea** [comment]
https://github.com/starkandwayne/safe/pull/226 opened for this issue.

**Comment by thomasmitchell** [comment]
#226 closes this
