### ISSUE TITLE
safe auth does not work on specified target

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/safe#217]
`safe -T different-target auth token` fails to record the token to the correct target.  It will instead override the current target's token in .saferc.  It does validate the token against the specified target though.  This is true when specifying a target via the -T option or by setting SAFE_TARGET environment variable.

**Comment by thomasmitchell** [comment]
addressed by 9c5211a661b60e185eebf70e74066be62296349b

**Comment by thomasmitchell** [comment]
released in v1.5.8
