### ISSUE TITLE
safe auth status command

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/safe#218]
For automation purposes, it is necessary to know if the current session is still authenticated.  `safe auth status` would be useful in this regard, either printing 'authenticated' or 'not authenticated', having a 0 or 1 exit code respectively.  Exit code 2 with a "unaccessible" output would indicate that it can't determine  the authentication status (can't reach the vault, internal issue, etc...)

Fancier version would be a string or json representation of auth type and time remaining if authenticated, with type of "Not Authenticated" and time remaining of 0 if not authenticated, but that may not be possible depending on what safe can access.

**Comment by thomasmitchell** [comment]
addressed by 5c510b6026cf86f1b707220c7e24fc5025bd2dbe

**Comment by thomasmitchell** [comment]
added in v1.5.8
