### ISSUE TITLE
`safe targets --json` missing namespace and strongbox entries

### ISSUE THREAD

**Issue by dennisjbell** [starkandwayne/safe#219]
Even though they are present in the .saferc, `safe targets --json` is missing entries for namespace and strongbox.  `safe target --json` contains strongbox entry, but is also missing namespace.

Note:  I tried to work around `targets` missing this information, by using `-T <target>` with `safe target`, but that didn't work because -T doesn't work with `target`.  Perhaps when used in the mode to get information about a target without setting it as the default target, -T does make sense to support.

**Comment by thomasmitchell** [comment]
addressed by 4c68409fed68b0e82f38b27afb1f7e3966fb1417
