### ISSUE TITLE
safe set failing to write files

### ISSUE THREAD

**Issue by kullcrom** [starkandwayne/safe#221]
When I try to `safe set` values, some fail to set seemingly at random. This used to work, and would set all values just fine, but it doesn't work anymore. Some files are written just fine, while others are not. They are valid files, and I have all necessary permissions. I have a script that writes the five files below consecutively using commands like the one below.
`safe set secret/eks/arnopd/ar-eks-np-1/certificates/ingress cert+chain@ar-eks-np-1-cluster-ingress.cert_plus_chain`

Currently targeting REDACTED-eks-tst at https://REDACTED/Vault/general/preprod/v2

Using namespace REDACTED-eks

Uses Strongbox at http://REDACTED.com:8484/strongbox

 

certificate: <ar-eks-np-1-cluster-ingress.crt

cert+chain: <ar-eks-np-1-cluster-ingress.cert_plus_chain

`!! Could not parse response body as JSON, and returned Content-Type is 'text/html'. Client may not be reaching Vault`

key: <ar-eks-np-1-cluster-ingress.key

pem: <ar-eks-np-1-cluster-ingress.pem

`!! Could not parse response body as JSON, and returned Content-Type is 'text/html'. Client may not be reaching Vault`

p12: <ar-eks-np-1-cluster-ingress.p12

`!! Could not parse response body as JSON, and returned Content-Type is 'text/html'. Client may not be reaching Vault`

**Comment by thomasmitchell** [comment]
The error is hitting a special case we put in to catch when a load balancer or DNS is doing _bad things™_ and not actually getting your traffic to the Vault server. The Vault server, unless you're hitting the Web UI, is pretty much always going to return a content type of `application/json`. If you run with `DEBUG=true safe set secret/my/cool/secret foo=bar` you might be able to tease out exactly where you're getting routed to based on the response you're getting.

**Comment by kullcrom** [comment]
Thanks @thomasmitchell

 

It appears that three calls are being made. The first two return `200`s. The first appears to be checking permissions/policies. The second appears to be reading the values at the path, at which I am attempting to add the new file. Finally, the third call fails with the `500` when attempting to write the file. The third call is below:

 

`

certificate: <ar-eks-np-1-cluster-ingress.crt

Request:

PUT //csg/processing/AIS/Vault/general/preprod/v2/v1/secret/data/eks/arnopd/ar-eks-np-1/certificates/ingress HTTP/1.1

Host: REDACTED.com:443

 

{"data":{"cert+chain":"REDACTED","certificate":"REDACTED","key":"REDACTED"}}

 

Response:

HTTP/1.1 500 Internal Server Error

Content-Length: 344

Connection: keep-alive

Content-Type: text/html

Date: Fri, 09 Oct 2020 23:28:45 GMT

Etag: "59a78f33-158"

 

<!DOCTYPE html>

<html>

<head>

<title>Error</title>

<style>

    body {

        width: 35em;

        margin: 0 auto;

        font-family: Tahoma, Verdana, Arial, sans-serif;

    }

</style>

</head>

<body>

<h1>An error occurred.</h1>

<p>Sorry, the page you are looking for is currently unavailable.<br/>

Please try again later.</p>

</body>

</html>

 

!! Could not parse response body as JSON, and returned Content-Type is `text/html'. Client may not be reaching Vault`

**Comment by thomasmitchell** [comment]
Not entirely sure, but could that be... Apigee?

**Comment by kullcrom** [comment]
I'm not sure either. I submitted a ticket with my company's vault team already and on Monday, I'll provide them with this additional information. It is certainly possible that they're fronting it with an Apigee proxy. Hopefully this will all make sense to them. Thank you for the help.

**Comment by thomasmitchell** [comment]
Closing this for now. Feel free to reopen if you feel like safe is causing this.
