### ISSUE TITLE
github auth is broken

### ISSUE THREAD

**Issue by forward32** [starkandwayne/safe#229]
Hi,

**Problem:**
```sh
Authenticating against test at https://vault.test/
Github Personal Access Token: 
Request:
POST //v1/auth/github/login HTTP/1.1
Host: vault.test

{"token":"my_github_token"}
----------------
Response:
HTTP/1.1 404 Not Found
Content-Length: 14
Cache-Control: no-store
Content-Type: application/json
Date: Mon, 16 Aug 2021 06:09:31 GMT

{"errors":[]}
```
At the same time I can successfully login using official vault client.

**Safe version**: safe (development build)

**Comment by thomasmitchell** [comment]
what version of Vault is this running against?

**Comment by forward32** [comment]
Version 1.7.2

**Comment by thomasmitchell** [comment]
are you, by any chance, `target`ing the URL with a slash on the end? Like, `https://myvault.com/`, as opposed to `https://myvault.com`? This appears like it would cause this oddity. That said, safe should really be more resilient to that, but if that's the cause, a workaround for you is to drop the trailing slash.

**Comment by thomasmitchell** [comment]
Okay, I think I've got a fix for this. Seeing as that you have a development version already, if you want to build the latest master and give that a shot I would be most appreciative.

That said, I was able to reproduce the issue, and post-fix, I can no longer reproduce it so... looking good.

**Comment by forward32** [comment]
Yes, a slash on the end was the reason of such behavior. Thanks for quick assistance!
