### ISSUE TITLE
Extend safe so it can initialize and unseal vault in HA or non-ha mode.

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/safe#34]
Extend safe to initialize and unseal vault.  Should deal with ha standby copies as well.

**Comment by jhunt** [comment]
This is mostly working for DNS (PR forthcoming), but we need to modify it to handle old-school Vault deployments as well as 0.6.0+ deployments.  This necessitates moving from DNS-based resolution to straight TCP/HTTP Consul API, a non-trivial undertaking.

**Comment by jhunt** [comment]
Just put in #58, as an alternative solution to this problem that plays well, but requires a new BOSH release.

**Comment by jhunt** [comment]
#58 is merged.  This will work if you are using strongbox with the safe-boshrelease
