### ISSUE TITLE
Vault PKI Backend Integration

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#37]
Some features that would be useful while interacting with the PKI  backend:

1. command for safe to generate a signed certificate (it would then store serial, cert, and key in the secret backend - keys aren't stored in the pki backend after they're created)
2. command for safe to revoke a signed certificate based on a secret backend path (or a serial number). If path was provided, look up the serial number stored there, and revoke that cert.
3. command to grab the CRL pemfile
4. command to grab the CA pemfile

Potentially other features for working with PKI roles, configuration, and CA creation?

**Comment by jhunt** [comment]
Is this handled by #38 ? (just merged)
