### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by mterron** [starkandwayne/safe#43]
Could you please add a Windows version?

**Comment by jhunt** [comment]
We can cross-compile for Windows, but I fear we lack the ability to adequately test a Windows version.

@geofffranks thoughts?

**Comment by geofffranks** [comment]
I'm curious how well certain functionality will work, especially related to things like `safe vault <cmd>`. Might just work, but might not..  If @mterron wants to provide testing/support for it, I'm game, but I don't think we have the bandwidth to provide it

**Comment by jhunt** [comment]
Next release should have a windows client attached!
