### ISSUE TITLE
Support `safe read /path/to/secret:key`

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/safe#49]
I want this to work:

```
$ safe read secret/handshake
--- # secret/handshake
knock: knock

$  safe read secret/handshake:knock
!! secret not found
```

Ideally, it works like this little spruce+jq pipeline:

```
$ safe read secret/handshake | spruce json | jq -r ".knock"
knock
```

**Comment by geofffranks** [comment]
Should that first try "handshake:knock" as a path, and get that, before failing back to "handshake" and its "path" key? Or is `:` a reserved character in all secret backends for vault?

**Comment by jhunt** [comment]
I don't know if `:` is usable in a Vault path, but Spruce doesn't handle them - per https://github.com/geofffranks/spruce/blob/master/op_vault.go#L141-L148, it would seem that a path like `secret/127.0.0.1:3000/admin:password` would be treated as a path of `secret/127.0.0.1` and an attribute name of `3000/admin:password`.

I think we should mimic that behavior, and if that's not the behavior we want, we ought to update Spruce to behave accordingly.

**Comment by thomasmmitchell** [comment]
If it makes you feel any better, scp uses this syntax and they pretty much threw in the towel on the problem. However, scp also appears to delimit by the last colon provided. Maybe thats the more logical way? I know you can technically make a yaml key with a colon in it, but... which is more likely to occur?

**Comment by jhunt** [comment]
I'm good with that, as long as we update Spruce accordingly

**Comment by geofffranks** [comment]
:thumbs-up:

**Comment by thomasmmitchell** [comment]
For posterity... this feature actually already exists in 0.23! Whoops... however, we'll be moving the secret:key separator to whatever the last colon in the string is, revamping the output for when it is found, and making a more sensible error for when it isn't found.

**Comment by jhunt** [comment]
still no joy, even after #51 😞 

```
safe read secret/handshake:knock
--- # secret/handshake:knock
knock
```

That's some YAML stuff right there.
