### ISSUE TITLE
safe -k is finnicky

### ISSUE THREAD

**Issue by geofffranks** [starkandwayne/safe#64]
Some minor issues:

- The `-k` flag doesn't seem to take effect when specifying the args as `alias url`, but does with `url alias`

**Comment by jhunt** [comment]
I see this for `safe help target`:

```
→  safe help target
safe target - Target a new Vault, or set your current Vault target
USAGE: safe [-k] target [URL] [ALIAS]
```

**Comment by geofffranks** [comment]
Me too. Looks like that was fixed back in november. Removing it from the issue
