### ISSUE TITLE
[alpine] bash: ./safe-linux-amd64: No such file or directory

### ISSUE THREAD

**Issue by drnic** [starkandwayne/safe#76]
On an alpine:3.5 container I installed safe but its giving this error:

```
curl -L https://github.com/starkandwayne/safe/releases/download/v0.1.3/safe-linux-amd64 -O
chmod +x safe-linux-amd64
./safe-linux-amd64
```

Error:

```
bash: ./safe-linux-amd64: No such file or directory
```

Same for v0.1.2.

Ideas?

**Comment by jhunt** [comment]
I suspect that the default network implementation requires libc for things like `gethostbyname` (which can't be statically compiled), and alpine is either musl, uclibc or dietlibc (can't remember which)

**Comment by geofffranks** [comment]
Is the safe pipeline not configured to build a static binary? Thought it was, but should be a simple fix if not.

**Comment by jhunt** [comment]
```
→  ldd safe-linux-amd64
	linux-vdso.so.1 =>  (0x00007fff5acda000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f07e1ee9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f07e1b20000)
	/lib64/ld-linux-x86-64.so.2 (0x000055602e2db000)
```

**Comment by geofffranks** [comment]
Pushed 9e180ba which should enable static binaries for the next release that will likely happen later today.

**Comment by jhunt** [comment]
Verified that safe 0.1.8 works fine within the confines of Alpine Linux Docker
