### ISSUE TITLE
Add `-R` / `--recursive` to `move` and `copy` actions

### ISSUE THREAD

**Issue by jhunt** [starkandwayne/safe#8]
`safe move` and `safe copy` should accept an option to recurse through subtrees and move/copy them as well.

**Comment by geofffranks** [comment]
Also for deletion.. deletion should add a -f flag, and prompt users (unless -f is specified) to confirm the vast number of deletions

**Comment by jhunt** [comment]
Did this get implemented?

**Comment by geofffranks** [comment]
Sure did. I'm just bad at github issues i guess
