### ISSUE TITLE
not authenticated

### ISSUE THREAD

**Issue by automaticgiant** [starkandwayne/safe#84]
i would think i could skip authentication by providing a `VAULT_TOKEN`, but this doesn't seem to work.
```
$ safe status
You are not authenticated to a Vault.
Try safe auth ldap
 or safe auth github
 or safe auth token
```
could it be masked by a silent cert validation error?
```
$ safe vault status
Error checking seal status: Get https://sdp-vault-dev:27003/v1/sys/seal-status: x509: certificate is valid for vault, not sdp-vault-dev
```
```
$ vault capabilities /
Capabilities: [root]
```

**Comment by jhunt** [comment]
Are you sure you have a `$VAULT_TOKEN` in your environment, and not a `.vault-token` file in your home directory?

**Comment by xanderrman** [comment]
@automaticgiant Have you checked into this? Thanks 👍

**Comment by automaticgiant** [comment]
no, sorry. hopefully next week.

**Comment by xanderrman** [comment]
no problem @automaticgiant, just wanted to check in :)

**Comment by jhunt** [comment]
Any update @automaticgiant ?

**Comment by automaticgiant** [comment]
Sorry, no. I've switched teams. Feel free to investigate or close.

_Sent from my Samsung SM-N920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jhunt** [comment]
Thanks!
