### ISSUE TITLE
safe find

### ISSUE THREAD

**Issue by thomasmmitchell** [starkandwayne/safe#87]
`safe find -name key` would find keys with name `key`.

Discussion points I can think of......
- What flags from normal find should be supported?
- Should we provide a way to search for keys within a secret?

**Comment by dennisjbell** [comment]
In PR #88 , we added the ability to list out all keys under a given path or paths.  This requested functionality can be achieved with a `|grep ':key$'`

**Comment by jhunt** [comment]
@thomasmmitchell is this still a thing we want to pursue?

**Comment by thomasmmitchell** [comment]
We can drop this one
